amc: rebuild bottles as opencv moved from gapi.4.0 to gapi.4.1
Reminder: `brew test` does not give the right error message:

    $ brew test auto-multiple-choice

    Error: maelvalais/amc/auto-multiple-choice: failed
    An exception occurred within a child process:
      Test::Unit::AssertionFailedError: <nil> expected to be =~
    <"TX=0.00 TY=0.00 DIAM=0.00\n">.

To see the actual error:

    $ auto-multiple-choice detect <<< ""

    dyld: Library not loaded: /usr/local/opt/opencv/lib/libopencv_gapi.4.0.dylib
      Referenced from: /usr/local/Cellar/auto-multiple-choice/1.4.0_1/lib/AMC/exec/AMC-detect
      Reason: image not found
    [1]    47670 abort      auto-multiple-choice detect <<< ""