fix: bump OpenSSL from v1.1 to v3 to resolve deprecation error
This change fixes the following error:
```
  Error: openssl@1.1 has been disabled because it is not supported upstream!
  It was disabled on 2024-10-24.
```

We now use OpenSSL v3 instead of v1.1.

This resolves:
1. https://github.com/maelvls/homebrew-amc/issues/94